version: '2'

services:
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - peer0.org1.example.com:/var/hyperledger/production
      - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/msp
    volumes:
      - orderer.example.com:/var/hyperledger/production
      - ./crypto-config/ordererOrganizations/example.com/users:/etc/hyperledger/fabric/msp
    ports:
      - 7050:7050

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - peer0.org2.example.com:/var/hyperledger/production
      - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/fabric/msp
    ports:
      - 9051:9051

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    command: /bin/bash
    volumes:
      - ./scripts:/scripts
      - ./config:/config
      - ./crypto-config:/crypto-config
    depends_on:
      - peer0.org1.example.com
      - peer0.org2.example.com
      - orderer.example.com

volumes:
  peer0.org1.example.com:
  orderer.example.com:
  peer0.org2.example.com: